### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by whmacken** [FLNRO-Smithers-Research/OffSite_Trials#1]
Use task list following

**Comment by Janewyx** [comment]
Original tasks:

- [x] Build[check] code to pull data from RESULTs using bcdata package

- [x] Extract example RESULTS data set : RSK region, Fd, Lw, Cw, Py species. See Tabular Data for information to retain

- [x] Spatial join sample to BECv11. Return Map_Label to dataset

- [x] Identify Offsite plantings: compare BGC x species of all blocks with Reference Guide Table. Retain records where no match

- [x] Summary stats of number of blocks and area sum planted by BGC x Species

- [x] Produce spatial output for GIS (.shp file) and tmap by species

- [x] Produce Shiny map showing locations of trials linked to tabular data

- [x] Add dashboard to allow filtering of trials by tabular fields
1. Species
2. BGC
3. Region
4. Planting Year
5. Source
6. Assessment Status
- [x] Use dashboard to allow online addition of other trial information
